### ISSUE TITLE
.MSI Installer

### ISSUE THREAD

**Issue by di48l069** [thoemmi/Solutionizer#86]
Hi @thoemmi 

What do you use to create .msi installer? Is it plugin on visual studio?

**Comment by thoemmi** [comment]
I'm using [WiX](http://wixtoolset.org/). The setup project is [Solutionizer.wxs](https://github.com/thoemmi/Solutionizer/blob/master/Solutionizer.wxs), and it is built by [Create-Release.ps1](https://github.com/thoemmi/Solutionizer/blob/master/Create-Release.ps1).

**Comment by di48l069** [comment]
@thoemmi Thank you
