### ISSUE TITLE
Exception when starting the app after installing v0.9

### ISSUE THREAD

**Issue by bneidhold** [thoemmi/Solutionizer#93]
i got this error in the logfile:

Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ShellViewModel (ReflectionActivator), Services = [Solutionizer.ViewModels.ShellViewModel, System.ComponentModel.INotifyPropertyChanged, Solutionizer.IShell, TinyLittleMvvm.IOnLoadedHandler, Solutionizer.Services.IStatusMessenger], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Settings (DelegateActivator), Services = [Solutionizer.Services.ISettings], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = SettingsProvider (ReflectionActivator), Services = [Solutionizer.Services.SettingsProvider], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = VisualStudioInstallationsProvider (ReflectionActivator), Services = [Solutionizer.Services.IVisualStudioInstallationsProvider], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'VisualStudioInstallationsProvider'. ---> Das System kann die angegebene Datei nicht finden (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Settings (DelegateActivator), Services = [Solutionizer.Services.ISettings], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = SettingsProvider (ReflectionActivator), Services = [Solutionizer.Services.SettingsProvider], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = VisualStudioInstallationsProvider (ReflectionActivator), Services = [Solutionizer.Services.IVisualStudioInstallationsProvider], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'VisualStudioInstallationsProvider'. ---> Das System kann die angegebene Datei nicht finden (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = SettingsProvider (ReflectionActivator), Services = [Solutionizer.Services.SettingsProvider], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = VisualStudioInstallationsProvider (ReflectionActivator), Services = [Solutionizer.Services.IVisualStudioInstallationsProvider], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'VisualStudioInstallationsProvider'. ---> Das System kann die angegebene Datei nicht finden (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = VisualStudioInstallationsProvider (ReflectionActivator), Services = [Solutionizer.Services.IVisualStudioInstallationsProvider], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'VisualStudioInstallationsProvider'. ---> Das System kann die angegebene Datei nicht finden (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor()' on type 'VisualStudioInstallationsProvider'. ---> Das System kann die angegebene Datei nicht finden (See inner exception for details.) ---> System.ComponentModel.Win32Exception: Das System kann die angegebene Datei nicht finden
   bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei Solutionizer.Services.VisualStudioInstallationsProvider..ctor()
   bei lambda_method(Closure , Object[] )
   bei Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   bei Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   bei Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   bei Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   bei Autofac.Core.Resolving.InstanceLookup.Execute()
   bei Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   bei Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   bei Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   bei Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   bei Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   bei Autofac.Core.Resolving.InstanceLookup.Execute()
   bei Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   bei Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   bei Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   bei Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   bei Solutionizer.AppBootstrapper.<>c.<ConfigureContainer>b__1_0(IComponentContext c)
   bei Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   bei Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   bei Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   bei Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   bei Autofac.Core.Resolving.InstanceLookup.Execute()
   bei Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   bei Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   bei Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   bei Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   bei Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   bei Autofac.Core.Resolving.InstanceLookup.Execute()
   bei Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   bei Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   bei Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   bei Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   bei TinyLittleMvvm.ViewLocator.GetViewForViewModel[TViewModel](ILifetimeScope lifetimeScope)
   bei TinyLittleMvvm.WindowManager.ShowWindow[TViewModel](Window owningWindow)
   bei TinyLittleMvvm.BootstrapperBase`1.OnStartup(Object sender, StartupEventA... Doppelklicken, um mehr zu sehen

**Comment by thoemmi** [comment]
Thanks for reporting. There are some DLLs missing from the setup. I'm working on it.

**Comment by thoemmi** [comment]
Fixed in 69378fe.
Please try [v0.9.1](https://github.com/thoemmi/Solutionizer/releases/tag/v0.9.1).
